controllers:
    resource: ../src/Controller/
    type: attribute

app_company_add:
    path: /company/add
    controller: App\Controller\CompanyController::addCompany
    methods: POST

app_company_list:
    path: /company/list
    controller: App\Controller\CompanyController::listCompany
    methods: GET

app_company_update:
    path: /company/update/{id}
    controller: App\Controller\CompanyController::updateCompany
    methods: PUT

app_company_delete:
    path: /company/delete/{id}
    controller: App\Controller\CompanyController::deleteCompany
    methods: DELETE

app_company_companyId:
    path: /company/{id}
    controller: App\Controller\CompanyController::companyId
    methods: GET

app_company_companyName:
    path: /company/name/{name}
    controller: App\Controller\CompanyController::companyName
    methods: GET

app_company_like_companyName:
    path: /company/like/{name}
    controller: App\Controller\CompanyController::likeCompanyName
    methods: GET

# app_jobs_id:
#     path: /jobs/{id}
#     controller: App\Controller\JobsController::getJobById
#     methods: GET

app_jobs_add:
    path: /jobs/add
    controller: App\Controller\JobsController::addJob
    methods: POST
    
app_jobs_list:
    path: /jobs/list
    controller: App\Controller\JobsController::getJobList
    methods: GET

app_jobs_update:
    path: /jobs/update/{id}
    controller: App\Controller\JobsController::updateJob
    methods: PUT

app_jobs_delete:
    path: /jobs/delete/{id}
    controller: App\Controller\JobsController::deleteJob
    methods: DELETE

app_jobs_jobName:
    path: /jobs/name/{name}
    controller: App\Controller\JobsController::getjobName
    methods: GET

app_jobs_like_jobName:
    path: /jobs/like/{name}
    controller: App\Controller\JobsController::getLikeJobName
    methods: GET