controllers:
    resource: ../src/Controller/
    type: attribute

app_company:
    path: /company
    controller: App\Controller\CompanyController::displayCompany

app_company_add:
    path: /company/add
    controller: App\Controller\CompanyController::addCompany